### ISSUE TITLE
[Discussion] Shoot hook rework proposal/ideas

### ISSUE THREAD

**Issue by direwolf420** [tModLoader/tModLoader#1008]
### Description
This issue is related to `ModPlayer.Shoot` and `ModItem/GlobalItem.Shoot` and their behavior. Ill outline some of the issues of its current implementation and some proposed fixes.

### Application Scope
Currently, both hooks are called in
```cs
else if (PlayerHooks.Shoot(this, item, ref vector, ref num70, ref num71, ref shoot, ref Damage, ref KnockBack)
	&& ItemLoader.Shoot(item, this, ref vector, ref num70, ref num71, ref shoot, ref Damage, ref KnockBack)) {
```
which is at the very end of the chain relevant for all projectile spawning from item use. A big number of valid shooting items (I would say about 50%, other modders agree with this number) won't ever enter this part of the code, making the hook useless if you want to detect projectiles being shot from items in a guaranteed manner. (Vanilla code is still inconsistent as to where it spawns projectiles sometimes, so it won't be able to cover 100% of items anyway, but even 80% is better than 50%)

Possible fix would be to add another hook with no return value that simply executes when an item was used to shoot a projectile (Possible overlap with UseItem (which is also a bit inconsistent because of item.useStyle logic, but that's another topic)).

### General Use
The hooks return value (bool) indicates if the game should proceed spawning the projectile with the given parameters or not.
Modders use this hook to change the way projectiles are spawned, or just spawn new ones entirely. In combination with how the hooks are called (ModPlayer ones being split from the Item ones), this can cause shortcircuiting due to the `&&`.

Possible fix would be to split up the logic into `CanShoot` and `Shoot` hooks. As for the shortcircuiting, change it to `&` or combine it into one `Loader` method.

**Comment by Mirsario** [comment]
> Possible fix would be to split up the logic into `CanShoot` and `Shoot` hooks.

Seems like the best solution to me.

**Comment by Ozzatron** [comment]
I very highly support splitting into `Shoot` and `CanShoot` and disabling the short circuiting. Calamity has needed to perform a few ugly workarounds for some items ignoring Shoot hooks (Minishark comes to mind) or tolerate it only working 90% of the time.

Similarly, numerous headaches relating to Calamity's Rogue class can be traced back to the one highlighted line of code with the hooks. This is especially problematic when unofficial Calamity expansions are installed because they tend to have their own projectile behavior code that isn't reliably called.

It seems clear to me that both changes will provide significant concrete improvements.

**Comment by JavidPack** [comment]
Note that various vanilla items not calling Shoot at all would not be fixed by the proposed fixes, the only way to fix that is to add code to each other if statement preceding this statement in the if else chain. Just a note to whoever works on this. Separating the hook into 2 might make this step easier to maintain

**Comment by Chicken-Bones** [comment]
The `Shoot/CanShoot` hooks need to be moved to `CombinedHooks.cs`
We also need to make a 1.4 thread for consistency in hook return values, call order, ref/out params and cancelling other mods.

`CanShoot` is necessary here, and simple, just return a bool to cancel _all_ shooting
Can someone describe several examples of how `Shoot` hook is typically used? It looks like people can do everything from change ammo, to trajectory, and damage/knockback. If all mods _only_ do these they're probably compatible, but I bet someone wants to add custom firing logic, or extra projectiles, or something. 

What happens when someone wants to cancel vanilla logic, because they're handling it themselves, but some mods haven't had a chance to modify the the damage values?

Do we need `ShootLogic` and/or `OnShoot` hooks?

**Comment by Jofairden** [comment]
`but I bet someone wants to add custom firing logic, or extra projectiles, or something.`
That's very common (example: shotgun)

`What happens when someone wants to cancel vanilla logic, because they're handling it themselves, but some mods haven't had a chance to modify the the damage values?`
I guess that'd need to become a diff hook
