### ISSUE TITLE
[Proposal] CanBurnInLava hook rework

### ISSUE THREAD

**Issue by direwolf420** [tModLoader/tModLoader#1040]
### Description
Currently in ItemLoader there exists the CanBurnInLava hook: `public static bool CanBurnInLava(Item item)`. This is the place where it's called: 

```cs
if (owner == Main.myPlayer && type != 312 && type != 318 && type != 173 && type != 174 && type != 175 && type != 2701 && rare == 0 || ItemLoader.CanBurnInLava(this)
```

 It returns false by default. Modders can override it and return true to force an item to burn in contact with lava, bar the vanilla exceptions above. Vanilla behavior is that items with a rarity of 0 (White) always burn bar the vanilla exceptions above. The hook is currently very limited in application scope: The only case where it makes sense to return true is if you want an item with higher than 0 rarity to burn.
If a modder would want to **prevent** items from being burned regardless of rarity, this is not possible via this hook currently.
A modder could instead "hack" the system and swap out the rarity in `ItemLoader.Update`, and change it back in `ItemLoader.PostUpdate`, but that's not in the spirit of tml.

### Proposal
Change the return type to `bool?`, similar to a bunch of other tml hooks, it would introduce new behavior:
* defaults to null: not overriding means vanilla behavior
* return true: force the item to burn regardless of any conditions
* return false: force the item to never burn regardless of any conditions

The place where it's called would have to be slightly changed to accomodate this.

### What does this proposal attempt to solve or improve?
More control over which items burn and don't without "hacking" the item rarity temporarily

### Which (other) solutions should be considered?
It will require a change of the return type, so this isn't sensible to do for current tml but for 1.4 tml.

**Comment by Chicken-Bones** [comment]
Makes sense. Last thing to specify is precedence. If one mod returns false and the other says true, does it burn?

**Comment by direwolf420** [comment]
* If more than one mod wants an item to burn, and no other mod wants an item to not burn, burn it
* If atleast one mod wants the item to not burn, don't burn it
Would be my suggestions

**Comment by JavidPack** [comment]
I think a mod that attempts to force some items to burn should take precedence. A mod like that would be implementing some sort of game mode, whereas a mod attempting to force an item to not burn is just suggesting some attribute of the item in question.

**Comment by Chicken-Bones** [comment]
> I think a mod that attempts to force some items to burn should take precedence. A mod like that would be implementing some sort of game mode, whereas a mod attempting to force an item to not burn is just suggesting some attribute of the item in question.

We have 3 use cases here:
- ModItem specifying whether it's "high quality" enough to not burn, or a GlobalItem increasing the 'quality' of a vanilla item
- GlobalItem giving more things immunity to burning, either globally or due to an accessory?
- GlobalItem forcing stuff to burn because of gamemode, lack of equipment, death, or [mechanic]

I think the notion of "don't burn me by default" is useful. Use case 2 should take precedence over 1, and 3 should take precedence over all. If use case 2 isn't required, then we can combine it into a general bool? returning hook. If use case 2 is required, then we need to make sure an item or global item setting 'default burnability' doesn't override an accessory trying to disable burning all together.

**Comment by Fragstiller** [comment]
This should probably be closed, since decent solution is merged now.
