### ISSUE TITLE
tModLoader v0.11.7.5 Error

### ISSUE THREAD

**Issue by OrianBatrov** [tModLoader/tModLoader#1103]
### Description
upon game start and error is displayed saying "..\Terraria\Terraria.exe is not the unmodified Terraria Executable"

### Log file
[client.log](https://github.com/tModLoader/tModLoader/files/5272980/client.log)

### Steps to reproduce

1. open app
2. error pops up

### Expected behavior 
tmodloder starts, mods are checked, then play

### Actual behavior
pops up error

### Reproduction frequency
Every time

### Additional Information
Full error

..\Terraria\Terraria.exe is not the unmodified Terraria Executable

GOG installs must have the unmodified Terraria executable to function

if you patched the .exe you can create a copy of the original exe and name it 
"Terraria_v<VERSION>.exe"

A client.log file containing error information has been generated in .\Terraria\ModLoader\Logs

**Comment by JavidPack** [comment]
Your log suggests everything worked as expected, and that you entered and played a world. The log is also from the 64 bit version, which suggest to me that you tried to revert to the normal tmodloader and forgot to delete all the files in the install directory. You need to do that since the 64 bit version you installed has some additional files that won't let normal tmodloader launch.

To reiterate: Just delete everything in the tmodloader install folder, then reinstall through steam
