### ISSUE TITLE
Git integration into setup

### ISSUE THREAD

**Issue by Agrair** [tModLoader/tModLoader#1127]
### Description
Git should be integrated directly into tML's "setup" app, or some git hook should be implemented?

### What does this proposal attempt to solve or improve?
`setup.bat` is expensive to run. Building the project every launch seems unnecessary to me (I know why it's there though). Instead, maybe there could be a new batch file called `buildsetup.bat` and `setup.bat` could just open the app? `buildsetup.bat` would do the things that `setup.bat` currently does but only has to be called when the dev has first pulled from the repo. I think the "Regenerate Source" function should come with a way to automatically pull the latest patches from upstream and apply them only to the files that got updated (hence putting into effect the same kind of date cutoff that diffing has). If there are some updates to setup itself, it will should close itself and call `buildsetup.bat` again. Is that possible? I don't know. I also think that Regenerate Source, if it utilizes the cutoff, should be able to distinguish branches so that when you switch, you don't have to regenerate source all over again as long as no new commits were made. If that makes sense. Ig devs can do that themselves though.

### Which (other) solutions should be considered?
A git hook that automatically calls `buildsetup.bat` whenever setup/ is updated. For the "Regenerate Source" function, the hook could also create a touch file in src/ that contains the current date of when the pull occurred.

**Comment by Jofairden** [comment]
Not entirely sure what is suggested here, but VS integration to do things automatically sounds tedious to write. I personally don't mind.

**Comment by Agrair** [comment]
It's the time to pull the submodules and build the actual app via dotnet that I don't like. I think those should only be updated when they *are* updated, but I'm not entirely sure if that's possible.

**Comment by JavidPack** [comment]
I tested it, it's 13 seconds on a fresh repository, and 5 seconds otherwise for setup.bat. We wanted to to clear the repo of binaries, since binaries aren't very nice to have in git. I'm not seeing this as a place where improvements would outweigh the effort and code maintenance costs.

As for patching only changed files, we could do that, but there is a slight issue where we don't quite trust the modified date of files. I think we just wanted to be absolutely sure that running the patches would 100% be a clean slate. If you implement a faster regen sources, it might be a tiny bit complicated to know all the files that should be there and delete those files and folders that shouldn't be there.

**Comment by Agrair** [comment]
Gotcha.

**Comment by Chicken-Bones** [comment]
I have something planned for improving the speed of the regen sources, but not for the git updates and setup tool building. If you can find a way to know if submodules are already up to date, then that'll help, but I don't see any good way around the "dotnet run" time. As jopo said, 5 seconds to setup boot (which is about the same for me) is pretty good for a build script anywhere.
