### ISSUE TITLE
tmodloader is silent for no reason

### ISSUE THREAD

**Issue by imabigboi** [tModLoader/tModLoader#1190]
just so you know i got terraria on steam because it is a lot easier to deal with.
for some reason tmodloader is completely silent while i try to play it even though:
1. tmodloader volume settings are at their correct numbers
2. volume mixer says it has the correct amount of volume
3. my master volume works
4. none of the mods i am using have been messing with the audio
5. tmodloader itself does not say anything about the bug.
6. RAM has enough space (if that has anything to do with it)
7. there is a good amount of space available in tmodloader
there is another thing that might be tied to the silence, for some reason while i was playing my character just froze in midair for no reason. all the NPCs and enemies were just fine.
please help.

**Comment by imabigboi** [comment]
i freeze when i go into the tundra biome, just so you know.

**Comment by alexandrefernandesoli** [comment]
same here, tried to reinstall everything (tmodloader, terraria, XNA Framework) and nothing worked

**Comment by StefanMarchhart** [comment]
The most recent update to the vanilla game changed:

`Content/Sound Bank.xsb`
and `Content/TerrariaMusic.xgs` among other things. 

I wouldn't be surprised if that broke the way TML handles audio since it uses the vanilla installs assets.
 
SteamDB for the Vanilla update is here https://steamdb.info/depot/105601/history/?changeid=M:7174777254123425714

**Comment by angeloleal** [comment]
Same here. Is there a way to restore Terraria to a previous version on Steam? That way we could at least avoid that problem until it is fixed.

**Comment by Soukyuen** [comment]
I am here to confirm that I am having the same issue here as well.

**Comment by imabigboi** [comment]
is there going to be a tmodloader update to fix this because absolute silence makes me feel uncomfortable and I NEED MY CALAMITY MUSIC!!! btw i think calamity might have a bug because i looked into it and apparently when you enter the tundra in death mode you are supposed to slow down and EVENTUALLY freeze if you don't have items to stop that like hand warmers, armors, etc. but i immediately freeze so the freezing in midair thing is a calamity bug, not a tmodloader bug.

**Comment by angeloleal** [comment]
I found a **temporary solution** that worked for me:
If you have a friend that has not updated the vanilla game yet, you can ask him to send to you the files on the "Content" folder, as well as the "Sounds" folder, then you use them to replace the ones on your vanilla terraria folder. That worked for me and the sound/music is working again. It seems that the "wave bank.xwb" file on the "Content" folder has some special influence on the sound problem, I tried at first without it because it is the bigger file in there and was taking so long to upload, and it did not work. The sound problem was only fixed when I replaced mine with the one my friend sent me.

**Comment by imabigboi** [comment]
i dont have any friends with the older version

**Comment by angeloleal** [comment]
I can upload my files if you want. But it will probably take a little while.

**Comment by Azdingo** [comment]
There is a way to download older version of the files through steam: https://www.reddit.com/r/Steam/comments/611h5e/guide_how_to_download_older_versions_of_a_game_on/

Currently trying with the following:
download_depot 105600 105601 7174777254123425714

The manifest ID was taken from there:
https://steamdb.info/depot/105601/manifests/

Will report back if it worked.

**Comment by Azdingo** [comment]
Using DepotDownloader worked!

I renamed the "Content" folder to "Content_old" and copied the one downloaded with DepotDownloader.

**Comment by imabigboi** [comment]
how do i use depotdownloader?

**Comment by Albhis** [comment]
depotdownloader also stumps me, what do I do?

**Comment by Azdingo** [comment]
Download it from here: 
https://github.com/SteamRE/DepotDownloader

Then run the following command from a command prompt (be sure to be in the folder where you extracted the zip file):
dotnet DepotDownloader.dll -app 105600  -depot 105601 -manifest 8445078731500628527 -username <username> -password 
<password>

**Comment by kinemoon** [comment]
I also don't understand how to use depotdownloader.
Mb gide for noobs?) ( ･_･)♡

**Comment by imabigboi** [comment]
btw i realized that the freezing in tundras thing has nothing to do with calamity death mode because i turned death mode off and went into the tundra and i still froze

**Comment by imabigboi** [comment]
how do i run the command?
sorry i am a little-brain when it comes to stuff like this

**Comment by Albhis** [comment]
I can't get it to work, I'm stuck on open zip file, shift right click master file. open power shell, paste command prompt, and it spits back 'command or file not found'. Am I even doing this right?

**Comment by Albhis** [comment]
Also where are you getting .dll from? the folder has an sln file or do I just know no basics

**Comment by CleansedHands** [comment]
Ok so:
1. I extracted the file
2. I opened it
3. I copied the folder directory
4. I opened Commands Prompt
5. I wrote "cd [directory of the folder] (it finishes with \DepotDownloader-master)
6. I wrote the code that Azdingo wrote in the comments
But it says "Could not execute because the specified command or file was not found"

**Comment by Mirsario** [comment]
Jopo is finishing the fixes for this as I speak.

**Comment by Mirsario** [comment]
This has just been fixed in 0.11.7.8.
