### ISSUE TITLE
Characters missing in-game

### ISSUE THREAD

**Issue by AisuTistoto223** [tModLoader/tModLoader#1213]
1. Open game and view characters.

### Expected behavior 

All characters in the files should be shown
### Actual behavior

Some of the Characters that are in the game files are NOT showing in the actual game despite being present in the files untouched.
### Reproduction frequency

Constant.
### Additional Information

I don't know what's happening

**Comment by JavidPack** [comment]
Read this <https://github.com/tModLoader/tModLoader/wiki/tModLoader-guide-for-players#my-worlds-and-characters-disappeared-when-i-installed>

If that doesn't apply, find the .plr and .tplr files and post them. They should be in the ModLoader/Players folder. If you are trying to load 1.4 players of players from the Terraria cloud save, those won't and should not show up.

**Comment by AisuTistoto223** [comment]
No, these are Characters that I have played modded with before. They have disappeared in game for no reason.  The files still exist. I restored the backup of those I could but not all of them have backups. I need this fixed

**Comment by JavidPack** [comment]
Post the files and I can tell you if they are corrupt. Or, you can check the ModLoader/Players/Backups folder to find zip files with backups in them, you can take the files from a zip and put them in the Players folder to test them, see if an old backup still works.

**Comment by Solxanich** [comment]
@AisuTistoto223 - I'd like to take the chance to check-in with you on this issue and if its already resolved.

Given that you haven't posted any files since, would I be correct in assuming that you were able to resolve the issue, or is this still an ongoing issue for you? 
If this issue is still ongoing for you, can you please provide any files or additional information to facilitate resolving this issue per JavidPack's comment?

**Comment by DeepBlue78** [comment]
im having the same problems, im attaching the file in a .zip, i have tried anything i can and it just doesnt work it just wont show up. i got another one from a few years back to show up but after i logged out, when i looked my stats had gone from max mana+400 hp back to the base 20mana and 100h
[Gia (1).zip](https://github.com/tModLoader/tModLoader/files/7738555/Gia.1.zip)
p

**Comment by Solxanich** [comment]
@DeepBlue78 - a couple of things.
1) Please open a new issue instead of posting on a closed issue. Isn't likely to be looked at.
2) First try the Discord if you haven't already https://discord.gg/tmodloader  . It is where help requests like yours gets answered. The github is more development focused
3) You can try restoring a backup if the player is from local files. If they were on steam cloud, thats a different matter. Again Discord is best help source
