### ISSUE TITLE
[1.4] Separate bestiary entries by mods

### ISSUE THREAD

**Issue by Mirsario** [tModLoader/tModLoader#1242]
### Description
A leftover of #1063. There were multiple discussions of whether or not modded bestiary entries should affect Zoologist's vanilla rewards, and the general consensus was that - no, they shouldn't. Mods that add bestiary entries should act as those entries' own categories, splitting the completion bar on bottom into multiple parts, like in the following artistic sketch:

![](https://i.imgur.com/Qehb7Vr.png)

Mods should have to implement their own rewards for filling of their bestiary entries, without forcing the players to fill thousands more of entries to get the same lame-by-that-time vanilla rewards that just weren't balanced for possibilities of having close to infinite amounts of content.

**Comment by kittenchilly** [comment]
Of course there should be a global bestiary count so people can make their rewards based on every mod if they want.

**Comment by imkSushi** [comment]
I'm not sure if this would look messy, but it is probably worth prototyping:

It might be an idea to split the bar horizontally too - the top half like the sketch above, but the bottom half collating by completed, not just mods, so that it is clearer what the overall fraction of completion is, or maybe a button next to the bar to switch between the two modes

**Comment by Mirsario** [comment]
Solved with #1368
