### ISSUE TITLE
[1.4] Index out of range exception in `Main.DoUpdate_AnimateItemIcons`

### ISSUE THREAD

**Issue by Eldrazi** [tModLoader/tModLoader#1279]
### Description
An index out of range exception in `Main.DoUpdate_AnimateItemIcons` as per the result of weird indexing.

### Log file
[client.log](https://github.com/tModLoader/tModLoader/files/5803178/client.log)

### Steps to reproduce
Very arbitrary, doesn't really seem to matter.

Bug occurs after clicking Build + Reload of ExampleMod.

### Expected behaviour 
The correct rebuilding of the mod and returning control to the user.

### Actual behaviour
Terraria in a permanent (until restarted) screen of blue.

### Reproduction frequency
Very sporadically. Sometimes on 1st rebuild, sometimes after 10th.

### Additional Information
Client log may show additional mods. The issue was also reproducible with just ExampleMod. More info also in Collaborators section of Discord.

**Comment by Solxanich** [comment]
Additional Information from Discord:
![image](https://user-images.githubusercontent.com/59670736/104345872-0a666680-54bc-11eb-9531-addc461618d4.png)
"My point of concern is that 'i' is correctly bounded, but num is not bounded (hence why line 395 instead of 392).  I'd have to look further into why the intermediary array is there, but I suspect the item Animations array is poorly implement for modded."

**Comment by Solxanich** [comment]
Alright, so the simple answer here for the Out Of Bounds error thrown is due to itemAnimations.Length being a fixed value in vanilla code of 5088, so item ids above that throw an error if running based on vanilla array size.

The long answer, including why the registered list could still point to a dead slot:
Vanilla array for itemAnimations is resized in itemLoader.cs; while mods are unloaded (as is the case when the issue comes up), it will default down to 5088.  
When we unload itemAnimations and default it to original size, we don't immediately clear the itemAnimations list until a little later. Meaning there could be a race condition occurring with the delay to cleanup the RegisteredList. A possible solution to this would be to move "Main.initializeItemAnimations" from ModContent.ResizeArrays to ItemLoader.ResizeArrays and place it to occur after Array.Resize(...itemAnimations...). This would likely eliminate any possibility of a race condition.

**Comment by Solxanich** [comment]
@Eldrazi - if the issue has been solved and it is no longer crashing, please let us know or close the issue.
Thanks!

**Comment by Solxanich** [comment]
@Eldrazi - if the issue has been solved and it is no longer crashing, please let us know or close the issue.
Thanks!

**Comment by Eldrazi** [comment]
Just did a breakpoint check to see if I could replicate the issue.

After 30+ rebuilds, everything still seems to be working fine, so I am assuming this has fixed the issue 👍

**Comment by Chicken-Bones** [comment]
@Mirsario the `lock` in your commit has no effect. You've reduced the chance of the race condition by moving the resize and wipe closer together, but not eliminated it.

Calling `Clear()` on `itemAnimationsRegistered` before resizing `itemAnimations` will prevent indexing with a mod item id, but you still run the risk indexing `itemAnimationsRegistered` when it's empty.

The only solution is to disable animations or pause the render thread during that part of unloading.

Is there any reason for item animations to run when `gameMenu` is true?

**Comment by Mirsario** [comment]
> the lock in your commit has no effect

hm? Does it only work if every single access is inside locks? I can wrap the update method in one with ease.

> Is there any reason for item animations to run when gameMenu is true?

There are item tags that people can use in mod descriptions, which show probably-animated item icons. No reason for them to be called during loading & unloading, though.

**Comment by Chicken-Bones** [comment]
correct, `lock` statements set a flag bit in the object header, which is only checked by other `lock` statements or `Monitor.Enter` on the same object. Wrapping the vanilla item animation update in a lock statement is also a good solution.

**Comment by Chicken-Bones** [comment]
Hmm, if an exceprion occurs before the Monitor.Exit call you will deadlock, monitor Exit is always called in a try finally (lock is just synyax sugar for this). A wrapper method can avoid indentation change
