### ISSUE TITLE
Audio does not work at all

### ISSUE THREAD

**Issue by HaxchiDev** [tModLoader/tModLoader#1433]
### Description
In-game audio does not play at all, and i do not know why.

### Steps to reproduce
1. Use [DLL Package.zip](https://github.com/tModLoader/tModLoader/files/6274634/DLL.Package.zip) and put the files in the game folder
2. Open the game
3. Audio just commits sudoku

### Expected behavior 
The game should play normally, since all the dependencies are met.

### Actual behavior
The game plays almost normally, but there is no audio.

### Reproduction frequency
100% of the time

### Additional Information
...I dunno.

**Comment by JavidPack** [comment]
I have no idea where you got that zip. The release works just fine, I'm not sure what you are hoping to accomplish with that assortment of dlls.

**Comment by MaximRq** [comment]
I have the exact same issue, and I tried the three latest tmod releases (didn't help). I'm using the GOG version of Terraria

**Comment by Mirsario** [comment]
(For Haxchi: assuming you've done a full reinstall of TML without those weird dlls.)
(For @MaximRq: please post a client.log file too.)

First of all - check if vanilla's audio works right.

XNA (the game framework that the game uses) is frequently quite terrible at detecting audio output devices (no wonder, it uses direct Windows kernel calls underneath itself.) If you're, say, using laptop speakers, plugging in headphones would frequently help. But there were cases when that wouldn't work either. If that's the case, my only blind guesses would be:
- Ensure that the device is correctly selected as the default (both communication & general) one.
- If you have Nvidia audio drivers - uninstall those.
- (Re)install Realtek HD audio drivers.
- Try using [64-bit TML](https://github.com/Dradonhunter11/tModLoader64bit/releases), as it uses FNA instead of XNA.

**Comment by Xianhui311** [comment]
Not too sure how helpful this is but you might want to ensure that your audio device is plugged in before you launch. Terraria doesn't update it's current sound device mid-game as seen [here](https://forums.terraria.org/index.php?threads/sounds-stops-working-on-device-change.90246/#post-1966620).

Looking at your logs @HaxchiDev, TML threw a [System.InvalidOperationException](https://docs.microsoft.com/en-us/dotnet/api/system.invalidoperationexception?view=net-5.0) on launch, as well as a [System.NullReferenceException](https://docs.microsoft.com/en-us/dotnet/api/system.nullreferenceexception?redirectedfrom=MSDN&view=net-5.0) upon loading your world. My knowledge of .NET (and by extension XNA) is pretty bad so I'm trying to piece together your intentions but my guess is that you are trying to make a portable version of TML, like in your [portable-terraria](https://github.com/HaxchiDev/portable-terraria) directory? Do you have the same audio issues with that? As mentioned in your previous [issue](https://github.com/tModLoader/tModLoader/issues/1427), your files seem out of place which is pretty odd. The issue is very likely related to that.

My guess is that your dlls are causing some issues with XNA's ability to create an audio engine. If you are trying to move all your games around, my suggestion is to get an external hard drive and install steam and all your games on that.

**Comment by Hotmud9** [comment]
> XNA (the game framework that the game uses) is frequently quite terrible at detecting audio output devices (no wonder, it uses direct Windows kernel calls underneath itself.) If you're, say, using laptop speakers, plugging in headphones would frequently help.

What I find interesting about this is that tModLoader's audio system on Mac is at least better than Starbound's. When the audio device changes whatsoever (aside from changing from the default speakers to something else; it just keeps outputting sound from the default speakers), the audio for the game stops working entirely, even if the device is plugged back in, and the game must be restarted or reloaded via commands in order for the audio to function properly again. The same can be said for Terraria 1.4, but for whatever reason, tModLoader handles audio device changes properly, both wired and Bluetooth.

**Comment by HaxchiDev** [comment]
> First of all - check if vanilla's audio works right.

The audio doesn't work on vanilla.

> My knowledge of .NET (and by extension XNA) is pretty bad so I'm trying to piece together your intentions but my guess is that you are trying to make a portable version of TML, like in your [portable-terraria](https://github.com/HaxchiDev/portable-terraria) directory? 

Yeah, but after I finish with the portable terraria.

>Do you have the same audio issues with that?

Yep. And it is extremely infuriating.

**Comment by Xianhui311** [comment]
If the audio doesn't work regardless of what version of Terraria you are running, it is most likely a dependency error. Make sure you have all the correct dependencies, my guess is you are missing the XNA audio framework.

Also for legal reasons I'm not sure your portable version is entirely legal. It might be considered pirating but I don't really know too much about that. Just a word of warning.

**Comment by HaxchiDev** [comment]
Wait... I forgot to ask where i could get the dlls.

**Comment by Xianhui311** [comment]
Honestly no clue, where did you get those dlls in the first place? Again, not familiar with .NET (and by extension XNA) so I don't really know.

That being said, Relogic.Native.dll (which can be found in the files of TML and/or Terraria), likely contains all necessary frameworks. This is just my educated guess, however, so can't guarantee anything. TML and Terraria both don't contain any dlls aside from what I assume are the ones from steam.

I still **heavily** recommend installing steam and all your games on an external hard drive. It should remove all issues like this. In addition if you are creating your portable version for use on a school owned device, this is very likely against their TOS. Be careful, and also edit your log files to not contain your school.

**Comment by HaxchiDev** [comment]
> Honestly no clue, where did you get those dlls in the first place? Again, not familiar with .NET (and by extension XNA) so I don't really know.

I got them from a Reddit post, don't remember which one tho...

**Comment by Xianhui311** [comment]
Not much I can do to help then. I'd advise to just do a normal install. You can move around the game files from there and functionally have a portable version. Only difference is your files won't carry over which can be easily solved. Pretty much all data can be found in Documents/My Games/Terraria. Modded and vanilla data can be found there. I'm also fairly certain you can just move your data to the cloud.

Again, after doing a quick search using details in your **publicly available** client logs that may contain **sensitive** information, your use of your device 100% violates clause one (Terms of Use of the Mobile Device) of your with the school county. I **heavily** advise you edit your issue to remove your client logs as this is functionally closed. I won't link your device agreement (which can be easily found through a quick google search), as that contains sensitive information, but you should probably stop breaking your device agreement, or remove information that can easily be traced back to you.

Assuming you do in fact legally own a copy of Terraria, you can also try moving Relogic.Native.dll into your folder and removing the rest of your dlls.

**Comment by HaxchiDev** [comment]
ok thanks for letting me know

**Comment by AnarchyBlues** [comment]
Sorry to necro this but I'm having the same issue as HaxchiDev and this is pretty much the only topic I've found on the matter. I'm trying to make a portable version of Terraria using the GOG version, I've extracted all the XNA 4.0 DLL's from the installer so I don't believe I'm missing anything from there. I've also added the revised OpenAL32.dll to the mix since that fixed a similar issue with Hotline Miami but I don't think Terraria actually uses OAL so I'm not surprised that didn't fix anything.

Terraria doesn't even appear under advanced sound settings in Windows, so it's pretty clear that a dependency is missing but I've hit a dead end as far as figuring out what that is.
