### ISSUE TITLE
Game crashes when opening door

### ISSUE THREAD

**Issue by Azazel-Woodwind** [tModLoader/tModLoader#1435]
### Description
When I try to open a specific door in an underground mushroom biome, the game instantly crashes and gives me an error message. This persists even with all mods disabled. Breaking the door works fine, though.

### Log file

[client.log](https://github.com/tModLoader/tModLoader/files/6278167/client.log)

### Steps to reproduce

1. Enter the world.
2. Jump down hellvator to the right of spawn to find first underground mushroom biome on the right
3. Open this door:
![image](https://user-images.githubusercontent.com/67590754/114018621-57f93200-9865-11eb-9c8f-0d596e428838.png)

### Expected behavior 

The door should open and break the rubble beneath it.

### Actual behavior

I hear the sound of the door opening, and also the sound of the rubble beneath the door breaking, but then the game crashes.

### Reproduction frequency

100% of the time.

### Additional Information

the error: ![image](https://user-images.githubusercontent.com/67590754/114018705-72cba680-9865-11eb-8a5a-0fe032ee9f80.png)
Mods used when loading the world:
Begone, Evil! v1.1.1
Bags v1.13.6
AlchemsistNPC Lite v1.7.4
LuiAFK v1.0.0.130
Fargo's Both Evils v3.1
Use Control to Quick Trash v1.1
Smart doors v1.3.3
Max Stack Plus Extra 1.1.0.4
Wing Slot v1.7.3
Which Mod is this From? v2.6.2
Mod Helpers v5.12.0
Magic Storage v0.4.3.5
Yet Another Boss Healthbar v1.3.2
VeinMiner v1.3.1
Calamity Mod Music v1.4.5.3
Recipe Browser v0.8.8.1
Boss Checklist v1.1.5.4
Calamity Mod v1.4.5.7
Zip of world files:
[Worlds.zip](https://github.com/tModLoader/tModLoader/files/6278247/Worlds.zip)

**Comment by direwolf420** [comment]
Similar issues exist in other cases, like with chests partly generating. The cause is clearly the faulty world generation, and not anything tModLoader is responsible for (hopefully). 

It would be helpful if you would provide a log file aswell:
You'll find the log files in the logs folder. Look for `client.log`. (NOT the .zip file, the file named client or client.log) 
**Windows Logs:** `%UserProfile%\Documents\My Games\Terraria\ModLoader\Logs` (This is typically found in C:\Documents\)
**Linux Logs:** `~/.local/share/Terraria/ModLoader/Logs/` or `$XDG_DATA_HOME/Terraria/ModLoader/Logs/`
**Mac Logs:**`~/Library/Application support/Terraria/ModLoader/Logs/`
