### ISSUE TITLE
1.4 support

### ISSUE THREAD

**Issue by thany** [tModLoader/tModLoader#1442]
### Description
The description of TML claims 1.4 support. How is 1.4 actually supported? It refuses to import my 1.4 character, and TML itself is Terraria 1.3.

### Log file
[client.zip](https://github.com/tModLoader/tModLoader/files/6289975/client.zip)

### Steps to reproduce

1. Install 1.4.1.2
2. Make a character & world
3. Install TML from Steam
4. Start TML
5. It literally says 1.3 in the bottom corner.
6. And indeed, your newly-created 1.4 character refuses to import.

### Expected behavior 
1.4 has been out for a while, so when a release claims 1.4 support, I expect that to be the case.

### Actual behavior
It doesn't support 1.4 at all. It's a totally separate Terraria instance, that's actually 1.3. There's literally nothing that could be called "1.4 support" with a straight face.

### Reproduction frequency
100%

### Additional Information
Installed Terraria and TML today for the very first time on this pc. There can be no lingering 1.3 parts anywhere on my pc.

**Comment by Itorius** [comment]
We clearly state that tML supports 1.4 installations, not that tML itself is 1.4 (you will have to wait for that)

**Comment by thany** [comment]
So it supports 1.4 in the sense that my pc doesn't catch fire if it's installed or something?

Stating 1.4 support doesn't make any sense if it doesn't matter at all.

**Comment by JavidPack** [comment]
Prior to the recent tmodloader updates, the changes to the Terraria 1.4 assets (music and textures) would cause tmodloader to not load, since the files changed in ways that the tmodloader code could not handle.  The message "Supports Terraria 1.4 installations - TML itself is 1.3 Terraria currently" means that even though your Terraria has updated to 1.4, tmodloader will now launch correctly despite the files changing. (tModloader reads the Terraria content files.)
