### ISSUE TITLE
[1.4] Rename character button flickers

### ISSUE THREAD

**Issue by cozykoko** [tModLoader/tModLoader#1489]
### **Steps to reproduce**

Just hover over the character rename button and you can see the tooltip flickering.

### **Expected behavior** 

 Tooltip should not flicker.

**Comment by Mirsario** [comment]
There is a lot of flickering bugs in vanilla that happen when you turn off frameskip with a more than 60hz monitor. Are we sure that this is TML's issue?

**Comment by cozykoko** [comment]
I tested this in vanilla and it was not the case.

**Comment by Steviegt6** [comment]
> There is a lot of flickering bugs in vanilla that happen when you turn off frameskip with a more than 60hz monitor. Are we sure that this is TML's issue?

Absolutely. It's an issue caused by a mistake in a patch I believe, making the text position use an incorrect variable that messes with its offset. It's overlayed on top of the rename button, causing flickering if you hover over the text, as it cancels the hovering of the button, which cancels the text and allows hovering again, rinse & repeat.

**Comment by cozykoko** [comment]
Fixed.
