### ISSUE TITLE
[1.4] Norton hates all the DLLs

### ISSUE THREAD

**Issue by BlueStaggo** [tModLoader/tModLoader#1494]
### Description

A minute after I unzipped tModLoader, Norton started scanning every DLL and removing all of them!

### Log file

I didn't even get to launch tModLoader.

### Steps to reproduce

1. Download tModLoader from [here](https://github.com/tModLoader/tModLoader/actions/runs/797777904).
2. Unzip the file.
3. If you have Norton, it removes all the DLLs.

### Expected behavior 

I expected the DLLs to stay there.

### Actual behavior

Norton removes them.

### Reproduction frequency

I'm pretty sure this is for forever until this bug is fixed.

**Comment by Solxanich** [comment]
There is some information on having Norton ignore the .dll here:
https://community.norton.com/en/forums/norton-detecting-dll-files-viruses-and-i-really-dont-know-how-fix-it

This is not a bug on our end; If I recall correctly, the act of downloading .dll and .bat/sh files from an internet site is known to set a flag on the file that it may be dangerous. Meaning what Norton is doing is entirely expected behavior.
If and when the files become downloaded through steam, then this will go away. 
Please use the workaround provided in link until then.

If the issue persists after being downloaded through steam, than this can be revisited as a bug

**Comment by BlueStaggo** [comment]
I've got Life Lock, not whatever that guy has. I can't see the word 'antivirus' anywhere.
![image](https://user-images.githubusercontent.com/71090710/116819576-87e7dc80-ab68-11eb-8f36-22f4307defe3.png)

**Comment by Solxanich** [comment]
"Click on settings as listed near the top of the opened dialog"
![image](https://user-images.githubusercontent.com/59670736/116828242-afd04380-ab5a-11eb-9354-9fd3efe4e95d.png)
Is anti-virus under there? You may wish to also do your own google search for your product specifically, as we aren't affiliated nor familiar with any or all Norton products, and the link provided was one of the first results.

**Comment by BlueStaggo** [comment]
Nothing I can do about this. I shall close this for now.

**Comment by Mirsario** [comment]
I don't know if this will affect norton, but, when 1.4 TML releases, it being downloaded by steam will give these files some legitimacy.

**Comment by BlueStaggo** [comment]
This thread will stay closed for now because Norton doesn't hate the latest release of 1.4 tModLoader.
