### ISSUE TITLE
Achievements and Play-time

### ISSUE THREAD

**Issue by IRonicBruh** [tModLoader/tModLoader#1540]
### Description
Please add the ability to merge tmodloader and terraria like before, So that we can earn Achievements and Play-time (towards terraria). This was possible in pervious versions... With the steam release that all changed for no real reason. I asked on the discord and it seems they aren't going to bring that back. Don't really understand why the ability to manual install is removed, The "Manual install guide" is really just a fix for the gog version and family sharing players, You still of to go thru steam.

### What does this proposal attempt to solve or improve?
A QoL really. You get your Mods and you get your Achievements and Play-time.

### Which (other) solutions should be considered?
A launcher just like before that runs tml thru the terraria.exe file. (I think that's how it worked)

**Comment by Chik3r** [comment]
I think you can make steam believe you are playing Terraria by going to the tModLoader install folder and replacing the number inside the `steam_appid.txt` file with `105600` (Terraria's steam id). This would make your play time go to Terraria, but won't help with achievements, since I think those were removed or disabled in tModLoader's code.
Also, the ability to manually install was not removed, and anybody can manually install as long as they follow the instructions in the install guide.

**Comment by Mirsario** [comment]
Adding or acknowledging support for this is anti-productive, as using a separate `appid` would mean not being able to play via steam networking with TML users who are on default configurations. And, now, there's an even bigger issue in 1.4 - making this work with steam workshop is an ever so giant can of worms.

The frankly experimental solution for playtime tracking in the above PR is too much shenanigans too.
