### ISSUE TITLE
ModHotkeys/ModKeybinds aren't localizable

### ISSUE THREAD

**Issue by Mirsario** [tModLoader/tModLoader#1566]
This is self-explanatory. Correct me if I'm wrong, but there doesn't seem to be a way of localizing keybinds, and they don't even have a separate display name, so people end up typing display names into the Id name parameter, since there's no other way.

**Comment by direwolf420** [comment]
This is now needed more than ever due to #2632 being merged.
Vanilla references keybinds within the localization file, tml currently doesn't offer that for modded keybinds.
Example:
`"If your Inventory is full, you can press {InputTriggerUI_Trash} and {InputTrigger_UseOrAttack} to send items to the Trash."`
![Screenshot_3](https://user-images.githubusercontent.com/15894498/191780376-ddac2c6d-1ecd-4e8d-80c3-89c0658afa02.png)
This likely needs furthering support for controller binds and displaying them dynamically

**Comment by JavidPack** [comment]
#2707 will take care of the localization deficiency, but DialogSubstitution will be it's own issue

**Comment by JavidPack** [comment]
#2964 will be the DialogSubstitution issue, it'll probably need some thought.

**Comment by JavidPack** [comment]
[d20a56a](https://github.com/tModLoader/tModLoader/commit/d20a56a00bb8de7cbaa4a28d81c58e55fcbbc674) implements this.
