### ISSUE TITLE
I want to use the unsafe mode

### ISSUE THREAD

**Issue by ColinWeiss** [tModLoader/tModLoader#1596]
How can I use unsafe mode for development?

**Comment by Chik3r** [comment]
What do you mean by unsafe mode? Do you mean that you want to use `unsafe` code in your mod? Because if so, it seems that you can enable `unsafe` code by passing `-unsafe true` as a start parameter to tModLoader
https://github.com/tModLoader/tModLoader/blob/b80ce364dccf013bad69bdddb5e8247903247e53/patches/tModLoader/Terraria.ModLoader.Core/ModCompile.cs#L661-L663

**Comment by ColinWeiss** [comment]
Thank you for your help ！！！
