### ISSUE TITLE
Will there be a mobile version

### ISSUE THREAD

**Issue by FriskGameZ** [tModLoader/tModLoader#1789]
### Is there an existing suggestion for this?

- [X] I have searched the existing issues

### Do you intend to personally contribute/program this feature?

No

### Description

Could there be a mobile version?

**Comment by Steviegt6** [comment]
No.

**Comment by Celestemysterios** [comment]
> No.

heres why there should be a mobile version
1. around 5 million people downloaded terraria on android (idk how many people downloaded on ios) and out of all of those people i doubt alot of them have terraria on steam
2. people see all of the fun mods on youtube and they probably wish they could play them, but they cant if they dont have steam. why should they have to rebuy the game on steam if they bought it on mobile and have to rebuy it on steam (tbh i wish it wasn't this way with other games also but oh well). like maybe make a separate modlist thing where mobile mods are shown so that way people can play mods that are mobile compatible
3. ~~please i really want to play mods like calamity so i can put myself though pain and torture i like pain~~
4. mods on the go
(also i replyed to this even though it was 3 years old because i was gonna make a issue requesting that but this already existed soo)
