### ISSUE TITLE
UI Way Too Small

### ISSUE THREAD

**Issue by Basic-Person** [tModLoader/tModLoader#1931]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest Official

### OS

Windows

### Platform

Steam

### Description

I have the UI scale to max, but the UI is still so small that it makes the game unplayable.

<img width="2555" alt="Screenshot 2021-11-02 134916" src="https://user-images.githubusercontent.com/90328949/139926873-95af3f73-9483-44bb-9d07-e999fba36872.png">

**Comment by JavidPack** [comment]
This might have been caused by WorldGen Previewer. If so, you can revert the changed setting that was erroneously changed:

> Revert the setting by opening "\Documents\My Games\Terraria\tModLoader\config.json" while the game is closed, finding the "SettingDontScaleMainMenuUp" setting (it should be around line 48), changing "true" to "false", save the file, then launch tModLoader again.

If that isn't the case, and you just have a really high resolution monitor, it might be intended. Feel free to reopen and post the client.log if you think it doesn't match up with other users with the same monitor resolution as you.
