### ISSUE TITLE
Feature: update mods with tModloaderServer.bin*

### ISSUE THREAD

**Issue by Finkregh** [tModLoader/tModLoader#269]
### Description

I'd like to update all mods via tModloaderServer

### Steps to Reproduce

1. start tModLoaderServer.bin.x86_64
2. open `Mod Browser` or `Mods Menu`
3. can't update mods

### Expected behavior 

it is possible to update all mods

### Actual behavior

updating mods is not possible

### Reproduction frequency

always

### Versions

v0.10.1

### Mods

not needed

### Additional Information

I joined the server w/o installed mods on the client and it installed all server-enabled mods. Now i see there are updates in the client...

**Comment by Jofairden** [comment]
What exactly do you mean? You wish the server feedbacks mod updates and can automatically update them?

**Comment by JavidPack** [comment]
Basically the suggestion is to implement the mod browser completely in the server CLI. It's not too big of a deal since most server owners would want to keep things on stable releases they know are working, updating only rarely, but we can easily add some options to the menu to show updates at the very least.

**Comment by JavidPack** [comment]
This is possible in the dedicated server scripts: <https://github.com/tModLoader/tModLoader/blob/stable/patches/tModLoader/Terraria/release_extras/DedicatedServerUtils/README.md>
