### ISSUE TITLE
Mod Browser not publishing

### ISSUE THREAD

**Issue by toshnika** [tModLoader/tModLoader#393]
When I go to the mod sources menu to publish my mod, I click publish. When I do this I briefly see "Uploading InitiateMod", followed immediatly by a screen saying "Publish using tmodloader" This might have to do with me being on linux.

Steps to reproduce (maybe)
1. Open Terraria (with tmodloader ofc)
2. Open mod sources.
3. Choose your mod source.
4. Build+reload
5. Click publish

the expected behavior was for the mod the uploaded to the mod browser. I checked and it isn't ther

Whenever I click publish, regardless of amount of times clicked or tmodloader version this happens

this has occured on tmodloader 0.10.1.1 where I build mods, and 0.10.1.5 where I play

 the only mods active are the the mod that is supposed to be published, as well as HERO's mod

**Comment by JavidPack** [comment]
This bug is quite a mystery. The only way to get "Publish using tModLoader" in the server code is if the steamid isn't sent when the mod is published. I'm not sure how this is possible, as my understanding is the steam integration will mean the steamid is always available for query. If we chat on discord I can probably do some logging on the server to find a hint in figuring this out.

**Comment by JavidPack** [comment]
jopojelly

**Comment by ZephaniahNoah** [comment]
This is also happening to me on Linux.

**Comment by Jofairden** [comment]
@Chicken-Bones with your recent endeavors on Unix, could you investigate this?

**Comment by wooden-utensil** [comment]
This is also happening to me on Windows, but it only happens 4% of the time! I just try to build & reload again and it works.

**Comment by Gcc07** [comment]
I just got the same bug!
