### ISSUE TITLE
Dowload xml documentation for reference assemblies

### ISSUE THREAD

**Issue by DRKV333** [tModLoader/tModLoader#631]
I would be nice if tModLoader could download xml documentation files for the reference dlls in `Terraria/ModLoader/References`, like it now does with `Terraria.xml`. It would be especially useful for MonoMod and Newtonsoft.Json to have usage hints in IntelliSense.

**Comment by JavidPack** [comment]
If anyone can find those xml files, we can probably do that.

**Comment by DRKV333** [comment]
Well, I haven't exactly found them, I had to extract most of them from the source code. Some of these xmls actually contain the full documentation, most of which is useless for IntelliSense. I can try cutting the remarks and examples bits out, if that's a problem.
[tModLoaderRefDocs.zip](https://github.com/tModLoader/tModLoader/files/3501069/tModLoaderRefDocs.zip)

**Comment by JavidPack** [comment]
I decided to just to the monomod xml files for now. I couldn't think of any reason a modder would benefit from the other xml files, at least at the cost of file size. The newtonsoft one might be useful, but I think it's too rare to be useful. 

We can revisit this later if it turns out my appraisal wasn't right.
