### ISSUE TITLE
GUI option to delete mod

### ISSUE THREAD

**Issue by TrueCP6** [tModLoader/tModLoader#640]
Currently the only way to remove a mod without just disabling it is to delete the .tmod file. A great feature would be having a GUI option to delete the mod from within the game to avoid having to navigate to the mods folder and deleting it manually.

**Comment by DarkLight66** [comment]
There's already a way to do this in-game, you just go to the mod you want to remove, ***make sure it's disabled***, then click on more info (?) and then delete. The only real problem is that it needs for the mod to be disabled beforehand and otherwise you wouldn't know the option even exists, not sure if this is a technical limitation or not.

**Comment by Jofairden** [comment]
Sounds like a good idea.
