### ISSUE TITLE
[BUG] Build & Reload's Unloading is flawed.

### ISSUE THREAD

**Issue by Mirsario** [tModLoader/tModLoader#663]
There's some difference between unloading from "Reload Mods" and "Build & Reload" buttons, with the latter causing 'ObjectDisposedException' crashes in mods that modify textures (or fonts?) of anything that's used in rendering of main menu (logos, backgrounds, stars, etc.)

**Reproduction steps:**
1. Get the incredibly simple source attached below. Build it, enable & load the mod.
**[UnloadTest.zip](https://github.com/tModLoader/tModLoader/files/3538019/UnloadTest.zip)**
2. See how using "Build" and then "Reload Mods" works completely fine.
3. See how "Build & Reload" crashes the game.

**Workaround I had to use in my mod:**
```cs
//At the top of a Main.OnTick subscriber method:
if(Main.menuMode==10006 && !OverhaulMod.mod.unloadCalled) {
	mod.Unload();
	return;
}
```
(What `unloadCalled` field is should be rather obvious.)

**Comment by Chicken-Bones** [comment]
Partial fix in commit above. You'll need to only modify the main logo on the main thread in unload though (and probably on load too), because those textures could be in use drawing a frame while you're changing them.

Here's a solution using TaskCompletionSource, though you can use whatever other thread synchronisation primitive you choose, including locks and flags.
[UnloadTest.cs.txt](https://github.com/tModLoader/tModLoader/files/3538110/UnloadTest.cs.txt)

**Comment by JavidPack** [comment]
Just a note, UpdateUI isn't called on the main menu, so I had to resort to UpdateMusic to solve a similar issue.
