### ISSUE TITLE
install files not found when attempting to update

### ISSUE THREAD

**Issue by milkev** [tModLoader/tModLoader#700]
Attempted to update to latest release (0.11.5) on windows, told files are not located and asks me to unzip the .zip file?... ive tried it in multiple locations on my harddrive, and redownloading the update multiple times but it fails to find the folders that are in the same location.
manual update did work, but i still thought it should be mentioned. just ignore/remove this if this is something that shouldnt be mentioned here.
![image](https://user-images.githubusercontent.com/22010128/67537128-5484e180-f697-11e9-8b04-6fc60278e792.png)

**Comment by JavidPack** [comment]
We can walk you through steps on discord if you want to investigate this: tmodloader.net/discord

From the information you have given, I can't tell what the issue is, but you might as well just do the manual install instructions from the readme.txt. We haven't had the installer fail for other users, so it must be something on your end.
