### ISSUE TITLE
AssemblyResolving can downgrade dependencies of dllReferences

### ISSUE THREAD

**Issue by tansheron** [tModLoader/tModLoader#764]
### Description
If an assembly in the mod's dllReferences line has a later version of a dependency than Terraria does, AssemblyResolving redirects it to Terraria's version of the dependency.

### Steps to Reproduce
1. Create a minimal mod project.
2. Create a new DLL project and give the mod project a project reference to it. Reference a type defined in the DLL project from the mod class's Load method to force assembly resolution.
3. Add a dependency on version 12.0.3 of Newtonsoft.Json to the DLL project. Terraria depends on version 10.
4. Use dllReferences to include the DLL project in the mod package.
5. Build the mod and load it when Terraria is launched.

### Expected behavior 
There should be no relevant warnings in the log file.

### Actual behavior
The log file contains a warning which says that version 12.0.0.0 of Newtonsoft.Json was redirected to version 10.0.0.0.

### Reproduction frequency
100%

### Additional Information
This code in AssemblyResolving checks only the display name of the dependency, not its version or strong-naming status:

```csharp
var existing = AppDomain.CurrentDomain.GetAssemblies().SingleOrDefault(a => a.GetName().Name == name.Name);
if (existing != null) {
	Logging.tML.Warn($"Upgraded Reference {name.Name} -> Version={name.Version} -> {existing.GetName().Version}");
	return existing;
}
```

It could be changed to never downgrade the version, but I don't think that's the right solution. tML doesn't know what the mod's needs are, so it shouldn't override the mod's version choices. Forcible upgrading or downgrading should be opt-in if they're supported at all.

**Comment by Chicken-Bones** [comment]
The conclusion we've come to in the past is that mods shouldn't be bundling the same assemblies as tModLoader due to a number of problems:

1. If you load the two side-by-side, the mod will be unable to access or communicate with any tModLoader code using types in the shared library. This rules out most of the libraries a mod might want to update.
2. Dependents of a mod with a duplicated tML library, will be pointed toward the mod version, and themselves be unable to communicate with tML (or other mods).

Perhaps you're in a situation where that's not a worry, but now that we have a pretty reasonable update cycle for tML, if there's an update to a library which you want, we can just update it in tML.

If it's backwards compatible, it can go in the next release. Otherwise, if you _really_ want to load a duplicate library side-by-side, just drop into dnSpy/cecil and rename the assembly (and possibly the root namespace too)

**Comment by tansheron** [comment]
OK, makes sense. I was able to downgrade to tML's version pretty easily.
