### ISSUE TITLE
Allow UI Scale < 1

### ISSUE THREAD

**Issue by Itorius** [tModLoader/tModLoader#765]
UI Scale bellow one should be allowed to make UI display properly on small displays.

**Comment by sgkoishi** [comment]
I made a patch to (partially) allow it but with many bugs two years ago.
It's done by IL transpiling, changing UI scale to 0-1 (instead of 1-2).
However, if you scale the game too small, you'll find the tiles far away from the screen centre will not be rendered.

Example (I didn't remember the exact number, just demo): 
UI Scale 33%
Only centred 1 / 2 tiles rendered
Only centred 2 / 3 NPCs rendered

Here's the patch if anyone want
```
// Terraria.IngameOptions::Draw
ldsfld float32 Terraria.Main::GameZoomTarget
ldc.r4 1 // => ldc.r4 0
sub

// Terraria.Main::get_RenderTargetsRequired
ldsfld float32 Terraria.Main::GameZoomTarget
ldc.r4 1 // => ldc.r4 0
bgt.s xxx

// Terraria.Main::UpdateViewZoomKeys
ldsfld float32 Terraria.Main::GameZoomTarget
ldloc.0
add
ldc.r4 1 //  => ldc.r4 0

ldsfld float32 Terraria.Main::GameZoomTarget
ldloc.0
sub
ldc.r4 1 //  => ldc.r4 0

// Terraria.Main::DoDraw
ldsfld float32 Terraria.Main::GameZoomTarget
ldc.r4 1 // => ldc.r4 0

// Terraria.Initializers.UILinksInitializer::HandleOptionsSpecials
ldsfld float32 Terraria.Main::GameZoomTarget
conv.r4
ldc.r4 1 // => ldc.r4 0
```

**Comment by Itorius** [comment]
Terraria has separate matricies (and scales) for the world and UI. But yeah, zooming bellow 1 for world would require to increase the drawn tile range.

**Comment by Jofairden** [comment]
This is now possible in 1.4, and will be possible when TML is on 1.4

**Comment by sgkoishi** [comment]
> 
> 
> This is now possible in 1.4, and will be possible when TML is on 1.4

Probably we should re-open this issue: by `UI Scale` we mean `Zoom (scale of the rendered map, players, npcs, projectiles)` instead of `UI Scale (scale of UI controls)`

**Comment by Jofairden** [comment]
UI = User Interface
