### ISSUE TITLE
My tmodloader keeps bugging the 6 key, no matter what item is selected after it goes to the 6 key

### ISSUE THREAD

**Issue by LeonardoCoelhoMoraes** [tModLoader/tModLoader#866]
My tmodloader keeps bugging the 6 key, no matter what item is selected after it goes to the 6 key.
It's not the keyboard!
It's not the Mods!
It's not the game!
È the tmodloader !!!

Meu tmodloader fica bugando na tecla 6, não importa o item selecionada depois ele vai pra tecla 6..
Não é o teclado!
Não são os Mods!
Não é o jogo!
È o tmodloader!!!

**Comment by Jofairden** [comment]
First of all, it helps if you speak english because everyone here speaks English. I'll use a translator in case you can't speak English.
When exactly did this start happening? After you installed a mod? Does this still happen without any mods enabled?

Primeiro de tudo, ajuda se você fala inglês porque todos aqui falam inglês. Vou usar um tradutor caso você não consiga falar inglês.
Quando exatamente isso começou a acontecer? Depois de instalar um mod? Isso ainda acontece sem nenhum mods ativado?

**Comment by LeonardoCoelhoMoraes** [comment]
it started to happen when i updated my tmodloader to the latest version!

**Comment by JavidPack** [comment]
We aren't sure why that might be happening, but you can try deleting `\Documents\My Games\Terraria\ModLoader\input profiles.json`, see if that helps
