### ISSUE TITLE
Pressing ESC within menus inconsistent

### ISSUE THREAD

**Issue by direwolf420** [tModLoader/tModLoader#874]
### Description
In vanilla, you can backtrack to the main menu by pressing Escape. If you are in certain tml menus, this is not possible. It is pretty inconsistent, here are some examples:
Escape works:
* tModLoader settings -> Main menu
* Mod Sources - >Main menu
* Mod Packs -> Mods
* Mod Description -> Mods

Escape doesn't work:
* Mods -> Main menu
* Mod Browser  ->  Main menu
* Mod Config -> Mods

**Comment by Shirkit** [comment]
I think a similar issue happens even ingame while playing Vanilla Terraria, I just noticed it again in 1.4

**Comment by JavidPack** [comment]
Fixed the Mod Config menu in da78441.

The Mods and Mod Browser menus both have a text box that doesn't need to be focused, so they will need more thought

**Comment by JavidPack** [comment]
As of now, Mod Sources, Mods, and Mod Browser menus all can't use the ESC button still. The issue is that PlayerInput.WritingText is true, meaning the esc/inventory key is ignored. Changing that to false means that the InputMode.KeyboardUI keys will be processed, which is also undesirable. Additionally, users can change the KeyboardUI.Inventory keybind to one of the alphabet keys, which would cause issues when searching.

The correct solution is to probably change those text inputs to require a click/focus to be used, but that would be unfortunate to their usability. 

Edit: Well, if we do this, we can properly support keyboard and gamepad navigation maybe, so it might be worth it.

**Comment by Chicken-Bones** [comment]
Good investigation, is there a way we can handle the Esc key specifically even when writing text? Either in the text box or via key-code?
