### ISSUE TITLE
tModLoader not downloading... Disk write issue...

### ISSUE THREAD

**Issue by KmonX** [tModLoader/tModLoader#904]
steam tmodloader wont download.. keeps saying disk write issue and i try manual still doesnt work...

**Comment by Mirsario** [comment]
Most likely you just don't have enough space on your disk. This isn't a tML issue.

**Comment by Jofairden** [comment]
What Mirsario said, or maybe you need admin privileges though I would find it uncommon for documents to be locked behind UAC.

**Comment by Jofairden** [comment]
Also please share the exact error

**Comment by JavidPack** [comment]
This seems to be related to antivirus quarantining the tModLoader.exe, falsely assuming it is a dangerous file.

We've had a report of a user disabling Avast and being able to avoid this issue. Rather than disable, I think most antivirus have whitelists/exclusion lists. Here is some instructions I Googled for Avast, there should be similar help documents for the antivirus you use: https://support.avast.com/en-ww/article/Antivirus-unblock-program-website

Here is another steam program that had a similar issue, this page links to info on various antivirus and how to allow a program to not be quarantined: https://steamcommunity.com/app/431960/discussions/2/143388132201188114/

**Comment by natethedude1038** [comment]
Thank you so much I have been very confused and I will try this now and post my findings soon

**Comment by natethedude1038** [comment]
ok i did some testing and yes it is avast blocking the download

**Comment by Solxanich** [comment]
Hello @KmonX ,
I'm currently reviewing stale issues, and would like to confirm if you are still experiencing this issue in the latest version 0.11.8.1 of tModLoader.
If not, could you please close the issue?
If so, could you please provide commentary on natethedude1038 and JavidPack's responses relative to your issue?

Thank you for your time.
